### ISSUE TITLE
2 Errors Reconnecting To Facebook: Permissions Error and Could Not Retrieve Facebook Business Extension System User

### ISSUE THREAD

**Issue by theabhig** [woocommerce/facebook-for-woocommerce#2148]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

There are 2 separate error messages, but I suspect they may be related so I have submitted these as a single issue.

My test site had an existing, working connection. These errors happened after I disconnected and tried to reconnect.

When I tested this on a site with a brand new connection, I wasn't able to replicate the issue and connected fine.

**First error** - `Permissions error: access_denied, reason: user_denied`

When I disconnected from Facebook and tried to reconnect from `WP-Admin > Marketing > Facebook`, I was first greeted by this screen:

<img width="517" alt="Screenshot 2022-02-03 at 08 47 54" src="https://user-images.githubusercontent.com/75635198/152320357-862cf2e5-9fa3-4ed1-afce-767c8b9c5488.png">

When I clicked on cancel, it gave me this error:

![Annotation on 2022-02-03 at 08-49-45](https://user-images.githubusercontent.com/75635198/152320480-09229798-1e5e-4a56-bd12-df2ba4e8a1b6.png)

And the connection wasn't established.

**Second error** - `Could not retrieve Facebook Business Extension System User`

After the first error, I went to `siteurl/wp-admin/options.php` and changed the `wc_facebook_external_business_id` field to a random string of 13 characters.

I then went back to `Marketing > Facebook` to try to connect again.

This time, I was able to go through the connection wizard on Facebook successfully.

<img width="514" alt="Screenshot 2022-02-03 at 09 23 25" src="https://user-images.githubusercontent.com/75635198/152320928-90a6ed6c-9fc3-4c72-88a4-6fefdbe8b4fb.png">

However when I clicked on `Done`, I was met with this error:

![Annotation on 2022-02-03 at 08-50-09](https://user-images.githubusercontent.com/75635198/152321027-8803b00a-ce98-40a0-8b0b-0cfd3d3c175d.png)

From the Facebook Business System Users, I can see a new system user was created and it has been granted access to my page, catalog, and pixel:

![Annotation on 2022-02-03 at 10-02-33](https://user-images.githubusercontent.com/75635198/152321226-bfd2be03-0b94-421f-8a87-12ea184586dc.png)

But it does not connect my site to Facebook Business Manager.

There isn't an option on my Business Manager to delete System Users but I also tried following the steps in the documentation to remove the app and extension completely and try again - https://woocommerce.com/document/facebook-for-woocommerce-uninstall-plugin-and-remove-woocommerce-facebook-app/ - but this also didn't work.

## 🚶‍♀️ Steps to reproduce

**First error** - `Permissions error: access_denied, reason: user_denied`

1. From a site with a working Facebook connection, disconnect the site.
2. Try to reconnect

**Second error** - `Could not retrieve Facebook Business Extension System User`

1. After following the steps for the first error, navigate to `siteurl/wp-admin/options.php` and change the `wc_facebook_external_business_id` field to a random 13 character string and press Save
2. Navigate to `Marketing > Facebook` and try to reconnect
3. Follow the prompts on the connection wizard and click `Done`.
4. This should generate the error `Could not retrieve Facebook Business Extension System User`

## ✔️ Expected behavior

The expected behaviour is that the extension will successfully reconnect to Facebook

## 🗃 Logs

The `42006` errors match the times I was getting the second error message.

```
02-03-2022 @ 08:50:59 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 08:51:39 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 08:57:20 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "AqIjd-lztvJBS6HgpzR1aRe"
}
02-03-2022 @ 08:57:33 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 08:59:35 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "AMml76WFHx0MpMy13mYvJWV"
}
02-03-2022 @ 09:07:55 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "A_exBfrGgs_H0B3Hofy85iQ"
}
02-03-2022 @ 09:21:43 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 09:21:56 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 09:23:34 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "ATQC5VpUg5MJwbw7ru9JTNz"
}
02-03-2022 @ 09:48:21 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied
02-03-2022 @ 09:50:28 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "ArNAt_OTePxJmZYcZoMuI6I"
}
```

<details>

`
### WordPress Environment ###

WordPress address (URL): https://theabhigfbtest.mystagingwebsite.com
Site address (URL): https://theabhigfbtest.mystagingwebsite.com
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.9
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.1
WC Database Prefix: wp_
Total Database Size: 4.38MB
Database Data Size: 2.38MB
Database Index Size: 2.00MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_hfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

afadv_qty: 1
attachment: 24
jp_pay_product: 1
page: 9
post: 1
product: 20
product_variation: 7
revision: 2
shop_order: 4
wc_order_status: 8
wc_pickup_location: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Facebook for WooCommerce: by Facebook – 2.6.9
WooCommerce Stripe Gateway: by WooCommerce – 6.1.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.22
WooCommerce: by Automattic – 6.1.1

### Inactive Plugins (13) ###

Addify - Advanced Product Quantity: by Addify – 1.2.0
Akismet Anti-Spam: by Automattic – 4.2.2
Header Footer Code Manager: by 99robots – 1.1.16
Jetpack: by Automattic – 10.7-a.1
WooCommerce Blocks: by Automattic – 6.9.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.2
WooCommerce Distance Rate Shipping: by Automattic – 1.0.26
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.4
WooCommerce One Page Checkout: by Automattic – 1.7.11
WooCommerce Order Status Manager: by SkyVerge – 1.13.2
WooCommerce PayPal Payments: by WooCommerce – 1.6.5
WooCommerce Points and Rewards: by WooCommerce – 1.6.43

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 220
Oldest: 2022-01-04 20:40:53 +0000
Newest: 2022-02-03 09:49:08 +0000

Pending: 3
Oldest: 2022-02-04 08:20:28 +0000
Newest: 2022-02-04 08:20:28 +0000

### Status report information ###

Generated at: 2022-02-03 09:50:48 +00:00
`

</details>

## Other instances

Similar errors have also been reported:

4724760-zen
4724725-zen
4742974-zen
4741909-zen
https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user/

**Comment by amElnagdy** [comment]
4724760-zen

**Comment by raifd** [comment]
[4704268-ze](4704268-zd-woothemes)

**Comment by amElnagdy** [comment]
https://wordpress.org/support/topic/permissions-error-access_denied-reason-user_denied/

**Comment by jobthomas** [comment]
I see that the latest release of Facebook is from 20 days ago - @theabhig @amElnagdy @raifd care to search Zendesk/forums back 20 days to see if this is connected to that release? (or is that the other instances/part)?

**Comment by raifd** [comment]
@jobthomas Just searched Zendesk and the first tickets regarding this seem to have appeared yesterday. I do not think this is related to the update!

**Comment by jobthomas** [comment]
Hmmm, is there another extension/core update that could cause this, or are we thinking this is on the Facebook side?

**Comment by raifd** [comment]
Is there any way we can find out what updates were pushed yesterday? My initial thought on this was some kind of Facebook Service being down, not sure though.

**Comment by theabhig** [comment]
It seems to only happen when reconnecting an existing connection. If it was something on the Facebook end being down, I would have thought it wouldn't allow me to set up a connection with a new site, but I was able to do that with no issue.

The earliest ticket I found was from Monday, which references the first error message:
4705156-zen

It did strike me as odd that we suddenly started seeing an influx in the last day or so when the extension was last updated a few weeks ago, which suggests it might be something on Facebook's end in terms of how they handle reconnection.

**Comment by anant1811** [comment]
I suspect this might be due to some changes on FB side, since on 4685206-zen — I was able to connect my own FB account without issue but the customer's account is returning the same error reported here. I've asked them to try and check if creating a new catalog helps, they still have to reply on that though.

**Comment by daniyalahmadk** [comment]
https://wordpress.org/support/topic/integration-with-facebook-3/

**Comment by narcisF** [comment]
Same issue for me!
Done the following:
*2FA Authentication enabled 
*website language  in english and currency is ok
*completely removed the WooCommerce App and System User
*disabled and deleted the plugin and deleted from mysql values with thi SQL cmd: DELETE FROM wp_options WHERE option_name LIKE ‘%wc_facebook_%’;
* disconected pixels from woocommerce
* added plugin again and setup again but i still got the error “Could not create a new System User” and the log:
02-03-2022 @ 17:23:03 - Failed to connect to Facebook. Reason: {
    "message": "(#42006) There was an error adding FBE\/EBC business assets to the system user.",
    "type": "OAuthException",
    "code": 42006,
    "fbtrace_id": "AoggGwzvhnnFIhGeYci388N"
}
* wc_facebook_external_business_id looks good now and before

**Comment by luanluta** [comment]
https://wordpress.org/support/topic/something-went-wrong-when-connecting-to-facebook-56/

**Comment by jrick1229** [comment]
https://wordpress.org/support/topic/algo-deu-errado-ao-conectar-ao-facebook-ou-something-went-wrong-when-connecting/

**Comment by jrick1229** [comment]
Not sure if this is related, but Graph API v5.0 expired on the same day when we started seeing these issues: https://developers.facebook.com/docs/graph-api/changelog/version5.0

**Comment by matecocidocontortafritas** [comment]
Hola, estoy teniendo el mismo problema desde temprano

**Comment by mariluciani** [comment]
Hi Guys,

Today the system works!
I was able to correctly reconnect!

Thank you
have a nice day

Marina

**Comment by matecocidocontortafritas** [comment]
El error sigue persistiendo, a alguno mas le sigue pasando? Gracias de ante mano

**Comment by teteraazul** [comment]
Prueba de nuevo, a mi me ha funcionado.

**Comment by FabricioCapelini** [comment]
the errors continue for me.

**Comment by matecocidocontortafritas** [comment]
![image](https://user-images.githubusercontent.com/98983910/152523563-863f841e-23f7-4f43-8fc9-2c0c05575505.png)

me sigue persistiendo este error

**Comment by moh04213** [comment]
> Hi Guys,
> 
> Today the system works! I was able to correctly reconnect!
> 
> Thank you have a nice day
> 
> Marina

the error continue for me, could you tell us what did you do ?

**Comment by 0xatok** [comment]
![image](https://user-images.githubusercontent.com/99028502/152553917-e52ae723-a797-4b0b-a504-f1117f055516.png)

**Comment by 0xatok** [comment]
before I had a problem like this
![image](https://user-images.githubusercontent.com/99028502/152554066-f46db114-acbb-4cbd-8634-57bec88f10e5.png)
Then I tried to reconnect but a problem happened like this.
![image](https://user-images.githubusercontent.com/99028502/152554758-22634b56-7a49-4213-84f3-0ba5229bef15.png)

**Comment by NathalyaVides** [comment]
Reported here too: https://wordpress.org/support/topic/facebook-for-woocommerce-doesnt-work/

**Comment by tysonL1010** [comment]
Bump, I have the same issue.

I had my facebook business manager/assets connected to an old shopify store, and I have since tried to migrate the connection to a new woocommerce/wordpress store. I think because my facebook busienss manager was already connected to shopify previously, it is causing errors when connecting to wordpress.

I am wondering if anyone else has these characteristics when facing the same issue?

**Comment by tysonL1010** [comment]
I have found a workaround. I can connect my facebook business account to wordpress, by using the facebook for wordpress plugin.

**Comment by rashedripon** [comment]
Reported here as well: https://wordpress.org/support/topic/pixel-is-not-integrated-into-my-page/

**Comment by delegacz** [comment]
> It seems to only happen when reconnecting an existing connection. If it was something on the Facebook end being down, I would have thought it wouldn't allow me to set up a connection with a new site, but I was able to do that with no issue.
> 
> The earliest ticket I found was from Monday, which references the first error message: 4705156-zen
> 
> It did strike me as odd that we suddenly started seeing an influx in the last day or so when the extension was last updated a few weeks ago, which suggests it might be something on Facebook's end in terms of how they handle reconnection.

Not really only for reconnects, This happens for me with a brand-new connection 
![err](https://user-images.githubusercontent.com/47157858/152785684-341a80df-7f56-4522-8721-20ae921d62e4.jpg)

**Comment by tysonL1010** [comment]
> Not sure if this is related, but Graph API v5.0 expired on the same day when we started seeing these issues: https://developers.facebook.com/docs/graph-api/changelog/version5.0

I did a little more digging and found this page. 

https://developers.facebook.com/docs/graph-api/guides/versioning

_"The goal for having versioning is for developers building apps to be able to understand in advance when an API or SDK might change. They help with web development, but are critical with mobile development because a person using your app on their phone may take a long time to upgrade (or may never upgrade).

Each version will remain for at least 2 years from release giving you a solid timeline for how long your app will remain working, and how long you have to update it to newer versions."_
 

As mentioned by [jrick1229] earlier in this thread, graph api v5.0 was discontinued on the same day issues started to arise. Can someone on the development team comment on whether the issues from the woocommerce plugin is related to v5.0 becoming expired?

**Comment by anant1811** [comment]
4715548-zen as well.

**Comment by pauljacobson** [comment]
We have reports here too:

- https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user-2/
- https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user-3/#post-15340723

**Comment by matecocidocontortafritas** [comment]
Es increible que aun esto este sucediendo.

**Comment by aheckler** [comment]
4757110-zen

**Comment by budzanowski** [comment]
> Can someone on the development team comment on whether the issues from the woocommerce plugin is related to v5.0 becoming expired?

The plugin is using API version 11.0 so this does not look related.
https://github.com/woocommerce/facebook-for-woocommerce/blob/master/includes/fbgraph.php#L29

**Comment by sukafia** [comment]
Typically, the first error `Permissions error: access_denied, reason: user_denied` is shown when the user doesn't grant FB permission (e.g started the setup & cancelled: https://d.pr/i/ng80zf)

* I'm only able to replicate the first error if I discontinue the setup 🤔 
* The 2nd error `Could Not Retrieve Facebook Business Extension System User` seems to only be applicable to old setups (I can't replicate it on a new setup) - that could mean it's caused by something that changed recently in the extension or on Facebook - it seems the issue is reconnecting to an existing business manager/catalog that was previously connected to the extension before recent changes. (Since I'm able to connect, disconnect & reconnect to a business manager/catalog that wasn't connected to the extension previously.)

**Comment by EtiennePoolman** [comment]
One more report in 4741909-zd-woothemes

**Comment by solstudioim** [comment]
Oddly, I wasn't able to replicate the problem (disconnecting an existing connection and reconnecting). 

Even, the I didn't see the first error, thus I didn't get the second error about the system user.

Here's the screencast: https://d.pr/i/exGiKk

**Comment by budzanowski** [comment]
One word of explanation. It is suspected what could be the reason we are currently seeing this issue but I needed some time to confirm. There were no changes to the plugin but there was one change to the connection bridge that is used to authenticate the plugin with the Facebook services. That change that was introduced was concerned, only, with what is being logged and how the logging is happening. No business logic was changed.

Previously all of the errors during the connection stage that have been observed have been lumped into one `Something went wrong when connecting to Facebook! Please try again.` And the details have been lost.

The connection is a multistage process and any of the stages could fail. With the recent change, each stage can generate a separate error. The gist of the error is what people are seeing currently under the `Something went wrong...` After clicking `Go back to my site` the plugin will catch all of the additional details from the connection process - this can be seen in the logs. Hopefully, this will allow reacting better, in a more granular way, to the problems merchants are facing.

**Comment by tamas-andrei** [comment]
![152785684-341a80df-7f56-4522-8721-20ae921d62e4](https://user-images.githubusercontent.com/96683400/153483392-4214e3eb-a806-4e3d-8abe-527425f00d5c.jpg)

02-10-2022 @ 13:30:00 - There was an error trying sync products using the Catalog Batch API for job 09d9d66f009bf40297202b601c577381: Cannot create the API instance because the access token is missing.
02-10-2022 @ 13:37:56 - There was an error trying sync products using the Catalog Batch API for job 1e2187859f400defe16f55e49d1d4fd1: Cannot create the API instance because the access token is missing.
02-10-2022 @ 13:38:04 - There was an error trying sync products using the Catalog Batch API for job 2797d1e61b645d879ea9fb4598239aea: Cannot create the API instance because the access token is missing.
02-10-2022 @ 21:07:19 - Unable to detect valid feed configuration: No catalog ID

**Comment by matecocidocontortafritas** [comment]
es increible que aun no haya una solucion para esto

**Comment by mehmetertugrul** [comment]
Hello, the problem still persists. All my 10 different woocommerce projects have the same issue. Urgent solution needed.

**Comment by tysonL1010** [comment]
Try Facebook for WORDPRESS. It seems to work this way

**Comment by mehmetertugrul** [comment]
Woocommerce for wordpress is a workaround but Facebook Conversions API is not working. This causes a lot of money to be spent in the advertising stages.

**Comment by tysonL1010** [comment]
you can set up conversion api through the facebook for wordpress plugin. It seems to be working fine unless you know something I don't

**Comment by Flyerg** [comment]
Hello, the plugin was connected, I had to disconnect it and when I try to connect it again I get the same errors. I already tried everything but I can't solve it, if someone finds a way please share, thanks!

**Comment by thracefulton** [comment]
And another instance in 4789752-zen

**Comment by EricaKuschel** [comment]
> 4757110-zen

I am having the customer try out the workflow.

**Comment by julonde** [comment]
I would like to help. Please, if someone is that nice and explain me what this "4789752-zen" is. (I am new here in Github) 
I have the same trouble since 7 Days. I tried everything, that was recommand and maybe even more, i doesn´t help. Sometime the Error Changed a bit but all in all the Shop does not connected to FB. 
With one Shop of my clients it´s working, on the other Shop it´s not. Unfortunatly they are too diffrent from the theme, plugin, installation and Co. to compare. On both Shops i installed the Woocommerce Facebook Plugin New - no Reconnection. As far as i know, this plugin was not in use ever on the Wordpress installations.

**Comment by ingibjorghil** [comment]
> It appears that the merchant in 4785585-zen was able to resolve their (suspected) instance of this error using the following steps:
> 
> 1. From Facebook Business Manager, navigate to More Tools → Business Settings → Brand Safety → Domains (alternatively, go to Commerce > All Tools > Business Settings > Brand Safety > Domains)
> 2. Use one of 3 options to `Verify your domain`.
> 3. Reinstall plugin/reinitialize the "Get Started" wizard
> 
> UPDATE: Another merchant, in 4789752-zen, attempted this process and was unable to resolve the issue.

Tried this but didn't work, "Could not retrieve Facebook Extension System User", always the same. 
It would be nice to know if someone one the development team is working on this or not? This issue has been open for almost 3 weeks now.

**Comment by julonde** [comment]
It´s possible that it is related to this here: https://github.com/woocommerce/facebook-for-woocommerce/issues/2154 When i chanced some settings, the "whoopsie" error comes up. But in a normal case, it should have worked, even with the new settings.

**Comment by luanluta** [comment]
Also reported here: 4788939-zen

**Comment by budzanowski** [comment]
We have reviewed some of the timeout policies we had for the connection process on https://graph.facebook.com APIs. It turns out that the timeout was set too low ( it was too aggressive ). We have bumped the values. This will not fix all of the issues but a subset of them. Please retry the connection process again.

 In case it still fails for you please provide the facebook connection logs ( only the recent logging attempt ) from the WooCommerce Status Logs section.

What we try to do now is to update the logging to gather as much information as possible.
Some of the issues that are being experienced are coming from the Facebook API server and need to be handled there. We want to build a verbose logging solution that will allow gathering all of the necessary data required by the Facebook support team to handle the connection issues.

**Comment by tamas-andrei** [comment]
02-21-2022 @ 21:33:34 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AgqcLhsCMenOSai-UTBKDsA"
}

**Comment by md-gh-user** [comment]
I have the same issue with Facebook for WooCommerce: "Could not retrieve Facebook Business Extension System User". Facebook for WordPress connected okay.

**Comment by budzanowski** [comment]
@tamas-andrei , @md-gh-user do you have 2FA enabled on your Facebook accounts? More info:
https://woocommerce.com/document/facebook-for-woocommerce/#two-factor-authentication

And in general, is there anything in the account quality section: https://www.facebook.com/business/help/254088759757736

Please write back if you found anything or you have been able to reconnect.

**Comment by md-gh-user** [comment]
Hi @budzanowski, I have 2FA enabled in FBM and there are no Account Quality issues. I just tried to connect again and got the same error: "Could not retrieve Facebook Business Extension System User".

**Comment by tamas-andrei** [comment]
@budzanowski 
Yes I have

**Comment by tamas-andrei** [comment]
![2FA](https://user-images.githubusercontent.com/96683400/155131220-a0663ff1-7cfb-4aca-9396-874b10d7b226.JPG)
Sory is in Romanian but is Active

**Comment by budzanowski** [comment]
@tamas-andrei You have posted the connection logs. Could you please clear all the FB logs from WooCommerce status, retry the connection and post the logs. Sorry for asking for the additional work but this is really valuable. I am gathering information that I will push to Facebook engineering to try to solve this. Most probably I will need to add additional logging to the code to gather even more information.

**Comment by budzanowski** [comment]
@md-gh-user is this a fresh connection? Or a reconnect attempt?
Is it possible to create and use a new Business Manager during the connection procedure?

**Comment by tamas-andrei** [comment]
For my no problem I will give all necessary.

02-22-2022 @ 15:35:51 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AsVx9HfRZXz8MiulpbZ8uyL"
}

**Comment by tamas-andrei** [comment]
I dellete compleat all logss and I try for 3 times.
02-22-2022 @ 15:35:51 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AsVx9HfRZXz8MiulpbZ8uyL"
}
02-22-2022 @ 15:39:26 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AsC1eblNP0J90VoDfHNjrAT"
}
02-22-2022 @ 15:42:14 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "A1DsXv7zA4iCb9JBfArPOYl"
}

**Comment by budzanowski** [comment]
@tamas-andrei what is the url of the site you are trying to connect?

**Comment by tamas-andrei** [comment]
https://norditech.eu/

**Comment by md-gh-user** [comment]
Here is my log data:

02-22-2022 @ 09:57:01 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AgySgeIChTpbqOu8rMact0d"
}
02-22-2022 @ 10:01:06 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AFHjmGH0jLoKXzYr_TKUXks"
}
02-22-2022 @ 14:25:37 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AR1MT_ExlupQi7WT89owKXG"
}
02-22-2022 @ 14:33:02 - Failed to connect to Facebook. Reason: {
    "message": "(#200) Permissions error",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "AluQgXcSpB0TseVy8wPeyVf"
}

Url is: https://www.hyprtrainer.golf

**Comment by md-gh-user** [comment]
> @md-gh-user is this a fresh connection? Or a reconnect attempt?
> Is it possible to create and use a new Business Manager during the connection procedure?

This is a reconnection attempt. The initial connection stopped syncing my products. I do not have another FBM account to use.

**Comment by mehmetertugrul** [comment]
Problem solved with version 2.6.10. Thanks everyone.

**Comment by matecocidocontortafritas** [comment]
Sigo teniendo problemas de conexion

**Comment by Snaacks** [comment]
https://wordpress.org/support/topic/technical-problems-with-the-plugin/#post-15393031

**Comment by thracefulton** [comment]
Another instance in 4788768-zen. I've asked them to update to 2.6.10 and confirm any changes.

Site: https://www.maison22boutique.com/
Version: 2.6.9

```
02-16-2022 @ 17:00:05 - Failed to connect to Facebook. Reason: {
"message": "This authorization code has been used.",
"type": "OAuthException",
"code": 100,
"error_subcode": 36009,
"fbtrace_id": "AuNcvUeGLcCdfoNR7tNeI1c"
}
02-16-2022 @ 17:00:57 - Failed to connect to Facebook. Reason: {
"message": "This authorization code has been used.",
"type": "OAuthException",
"code": 100,
"error_subcode": 36009,
"fbtrace_id": "AQLkqey-3lJKTk03BdMhB4r"
}
02-16-2022 @ 17:32:49 - Failed to connect to Facebook. Reason: {
"message": "This authorization code has been used.",
"type": "OAuthException",
"code": 100,
"error_subcode": 36009,
"fbtrace_id": "AGIxOlxwiG4C1F7smHcZLU7"
}
02-16-2022 @ 18:29:07 - Failed to connect to Facebook. Reason: {
"message": "This authorization code has been used.",
"type": "OAuthException",
"code": 100,
"error_subcode": 36009,
"fbtrace_id": "Au_4wAupp3FennyxZ75yeJw"
}
```

**Comment by Kukiman0** [comment]
I am facing the exact same issue with #200 permission, 

https://wordpress.org/support/topic/product-sync-problem-permission-error-200/#post-15394308

Updated wordpress, facebook for woocommerce, woocommerce database, issue still occurs.

**Comment by md-gh-user** [comment]
Updated to version 2.6.10. Still getting code 200 error.

**Comment by budzanowski** [comment]
@md-gh-user The error code 200 means that there are insufficient permission scopes granted to the app during the connection flow. Could you please review all the steps and check if all of the permissions are set? I assume that they are but I am just double-checking.

Additional questions: are you setting up the connection with Instagram shopping enabled?

**Comment by tamas-andrei** [comment]
I try with Instagram shopping enabled also disabled.
About insufficient permission? what I have to cheack? the page is linked to my acount I have full access

**Comment by Kukiman0** [comment]
I have also checked all the permissions, I do not have instagram or facebook shopping enabled. I went through the permisison settings multiple times, eveything seems fine there.

**Comment by budzanowski** [comment]
That is the problem actually. All of the permissions during the connection are selected on the setup screens and at the same time, the Facebook graph server claims that some permissions are missing, hence the 200 error. I am trying to figure it out with Facebook engineering.

**Comment by narcisF** [comment]
Updated to Version 2.6.10 but i have the same error: Could not retrieve Facebook Business Extension System User. Uninstalled plugin, deleted values from mysql (DELETE FROM `wpv_options` WHERE option_name LIKE '%wc_facebook_%';), deleted WooCommerce Integration from https://www.facebook.com/settings?tab=business_tools&ref=settings, created a new catalog, installed again and setup but the error is the same. log for Could not retrieve Facebook Business Extension System User :
02-23-2022 @ 13:30:40 - Failed to connect to Facebook. Reason: {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
    "fbtrace_id": "AGY84oO6IRQRA5_tQQ2yzvY"
}
Brand safety is ok, account quality also ok. Unchecked instagram durring setup. After that i tried the facebook for wordpress plugin but I have almost the same error:
Something Went Wrong
An error occurred while fetching system user access token:{ "error": { "message": "An unknown error has occurred.", "type": "OAuthException", "code": 1, "fbtrace_id": "AuXa_U8I6T0IPZAUv5ENP3Z" } }

Is there anything else I can try?

**Comment by budzanowski** [comment]
@narcisF `An unknown error has occurred.` that is a failure of the Facebook server of some sort. Looks not related to the apps.

**Comment by md-gh-user** [comment]
> @md-gh-user The error code 200 means that there are insufficient permission scopes granted to the app during the connection flow. Could you please review all the steps and check if all of the permissions are set? I assume that they are but I am just double-checking.
> 
> Additional questions: are you setting up the connection with Instagram shopping enabled?

Hi, yes, I am using all the default settings on the wizard. The Instagram shopping box is TICKED.

**Comment by narcisF** [comment]
@budzanowski The "An unknown error has occurred" from logs is when " Could not retrieve Facebook Business Extension System User" error appears. Also when creating a new catalog, which option is the correct one: Checkout on Facebook and Instagram
 OR Checkout on my Website?

**Comment by thelogicwizards** [comment]
4788842-zd-woothemes

**Comment by tysonL1010** [comment]
any updates?

**Comment by lautaropiatti** [comment]
I'm having the same issue.

**Comment by Kukiman0** [comment]
Any updates? I also tried disconnecting and reconnecting to my website and now I can't even reconnect, I am getting some errors saying that I am not the admin, I do not have permissions etc.

**Comment by voxoff79** [comment]
Any updates?  facing the same 200 permissions issue.

**Comment by tamas-andrei** [comment]
In my case the problem was solved, after last update I can connect.
Thank you

**Comment by Flyerg** [comment]
I updated to the latest version, and after a couple of days of trying, it fixed itself.
Thank you

**Comment by asalah0707** [comment]
I keep trying for many days and updating the plugin twice and no progress, that was after contacting FB support also.
recently I discovered that there's an issue with 2FA from the Facebook side when I changed the browser to a new one never logged FB on it and tried connecting the app and logged in to FB and there I found out I don't get the code and accepting the new Device login doesn't pass the code screen.
Please can somebody confirm?

**Comment by budzanowski** [comment]
Anyone is still experiencing the OAuthException code 200 error?

**Comment by budzanowski** [comment]
@voxoff79, @lautaropiatti, @tysonL1010, @md-gh-user 

Is the error still happening?

Anybody else?

**Comment by md-gh-user** [comment]
> @voxoff79, @lautaropiatti, @tysonL1010, @md-gh-user
> 
> Is the error still happening?
> 
> Anybody else?

Hi, managed to connect okay now. My product does not seem to be synced but that maybe a different issue.

**Comment by asalah0707** [comment]
> @voxoff79, @lautaropiatti, @tysonL1010, @md-gh-user
> 
> Is the error still happening?
> 
> Anybody else?

Yes Same here

**Comment by budzanowski** [comment]
@asalah0707

> Yes Same here

Do you mean that the error is still happening or do you mean that you have been able to connect?

**Comment by budzanowski** [comment]
@asalah0707 could you share the error logs ( please retry again and fetch recent logs ) and your Facebook user ID ( https://www.facebook.com/help/1397933243846983 )

**Comment by asalah0707** [comment]
850195093
03-02-2022 @ 09:03:22 - Failed to connect to Facebook. Reason: Permissions error: access_denied, reason: user_denied

**Comment by budzanowski** [comment]
@asalah0707 OK, one more request ( sorry ), could you show the last screen on the login flow, the buttons, and what you click before you are redirected and see the error?

Some users have been shown a different screen from FB than we normally have and we are trying to figure out what is happening and why some users are going through a different flow.

**Comment by budzanowski** [comment]
@asalah0707 if this is a 2FA problem then there is nothing we can do about it here. The Facebook 2FA is controlled by Facebook exclusively so you need to contact Facebook support for resolving the issue.

**Comment by asalah0707** [comment]
> @asalah0707 if this is a 2FA problem then there is nothing we can do about it here. The Facebook 2FA is controlled by Facebook exclusively so you need to contact Facebook support for resolving the issue.

I already did that but maybe also from the plugin side there's something to do

**Comment by shohanhossainnab** [comment]
Another report: 4834252-zen

**Comment by budzanowski** [comment]
@shohanhossainnab Which issue exactly? There are two distinct problems in this GH issue, and they are separate actually.

**Comment by shohanhossainnab** [comment]
It's `Permissions error: access_denied, reason: user_denied` for this user.

**Comment by ibenster** [comment]
I'm getting the same Permissions error on two different sites, after I removed the plugin, used the cleanup tool, inspected the database manually.

`Permissions error: access_denied, reason: user_denied`

**Comment by budzanowski** [comment]
When this happens the `Return To WooCommerce Integration` button does not do anything, yes?

**Comment by ibenster** [comment]
Yes, and if you press ESC during the integration process you get the mentioned error.

**Comment by shohanhossainnab** [comment]
> When this happens the `Return To WooCommerce Integration` button does not do anything, yes?

That's the case exactly with the user in 4834252-zen

**Comment by budzanowski** [comment]
I am sorry to inform but that the login flow is out of the plugin control. This code is controlled by Facebook directly. They have been notified and they have assigned the problem to an internal team for investigation and resolution. The only thing that we can do is to put pressure on them. For reference, this is a link to the issue ( accessible only if you have developer access to Facebook business ) https://developers.facebook.com/support/bugs/1193345714737751/?join_id=f63ee735660ab

**Comment by thracefulton** [comment]
@budzanowski Just to clarify, this means that resolutions for both errors are in Facebook's court at this point, correct?

**Comment by ibenster** [comment]
I can confirm that the latest update (2.6.12) fixed the problem on three separate instances. 🏆

**Comment by budzanowski** [comment]
A lot of the connection problems have been fixed by the Facebook team. I am closing this Issue.
If you still experience login problems and happen to end up here please open a new Issue ( or check other open issues for similar problems ). I am not trying to be dismissive but we have too many different problems in the same thread and it has become hard to track what is what. We will be able to assist better this way.

**Comment by spraveenitpro** [comment]
Another one https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user-6/

**Comment by gabrielbonifacio** [comment]
I got two other instances: 4870683-zen and 4923073-zen

**Comment by djaysan** [comment]
I have tested everything from this ticket and still get 'Could not retrieve Facebook Business Extension System User'
here is my wp ticket: https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user-6/

**Comment by corvistr** [comment]
I have the same problem and it's very annoying. I tried all ways but it didn't work. It seems to be connected in business suite, but it gives an error on the woocommerce side.

**Comment by djaysan** [comment]
the new plugin update fixed my issue

**Comment by rawdreeg** [comment]
Thanks for confirming @djaysan. We addressed a lot of the onboarding issues in the last release. 

We've also received a report of the issue being solved on the WP.org forum thread. I will close the issue. Feel free to re-open if you're still experiencing the ` Could not retrieve Facebook Business Extension System User` error.

**Comment by melek** [comment]
This problem is still affecting WordPress.com users on the most recent version of Facebook for WooCommerce (2.6.13).

35294002-hc / 5176206-zen

They get the 'Could not retrieve Facebook Business Extension User' error, and the following error in their logs:

```
04-28-2022 @ 12:32:10 - Failed to connect to Facebook. Reason: {
    "message": "Application does not have permission for this action",
    "type": "OAuthException",
    "code": 10,
    "error_subcode": 2859015,
    "is_transient": false,
    "error_user_title": "Your account is restricted right now",
    "error_user_msg": "You have been temporarily blocked from performing this action.",
    "fbtrace_id": "A1e4EP0Qlcss9dITohWhfBx"
```

**Comment by rawdreeg** [comment]
@melek Thanks for reporting (with additional information). I will have a look and keep this thread updated.

**Comment by baltrau** [comment]
> > I can confirm that the issue still persists. It seems like the issue rises when trying to reconnect an account that was previosly connected.
> > I ran the SQL to clear wp_options, installed / uninstalled the plugin, tried with the older version that facebook provides, the error is still the same.
> > `Could not retrieve Facebook Business Extension System User`
> > The log from woocommerce:
> > ```
> > 04-29-2022 @ 15:18:38 - Failed to connect to Facebook. Reason: {
> >     "message": "An unknown error has occurred.",
> >     "type": "OAuthException",
> >     "code": 1,
> >     "fbtrace_id": "ABQpEucjoL1Fn5gh7VtQT8Y"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Facebook for Woocommerce plugin version: 2.6.13 Wordpress version: 6.4.1
> 
> @baltrau thanks for confirming. any chance you could share with me the return auth URL as described here:
> 
> [#2148 (comment)](https://github.com/woocommerce/facebook-for-woocommerce/issues/2148#issuecomment-1104082463)
> 
> Thanks

`%26nonce%3D47ae67961f%26type%3Dstandard#_=_`

**Comment by CBGharios** [comment]
Hello, 
Any update on this issue?
I am still having the same error (user_denied)

**Comment by asalah0707** [comment]
I'm still contacting the FB team and they still can't give a solution i wish someone from the Automattic team check the business account permission and the app permissions on FB developer account

**Comment by rawdreeg** [comment]
@CBGharios,
@asalah0707 

We've been talking to Meta about this issue. They're currently investigating the issue as it seems to be affecting users who have existing connections to the WooCommerce Integration FB business app.

Some users have had success with uninstalling the app on FB and reconnecting:

- Navigate to https://business.facebook.com/latest/business_app_store/ 
- Select the WooCommerce Integration and click on Manage

![Screenshot 2022-05-23 at 14 20 41](https://user-images.githubusercontent.com/4209011/169818025-19c12978-8020-4c0f-a301-c1c821ed9874.jpg)

- Click on the three dots and try to reinstall. If you have any issues with this please contact the Business support

![Screenshot 2022-05-23 at 14 18 39](https://user-images.githubusercontent.com/4209011/169817715-8b67704a-33c6-46e9-82bd-d15c6ab65071.jpg)

**Comment by maxlaf** [comment]
Another report of `Could not retrieve Facebook Business Extension System User` when reconnecting in 5272814-zen. The merchant is using 2.6.15. They've said the Integration App and System User aren't present in Facebook.

**Comment by wyter** [comment]
5247887-zd-woothemes

**Comment by amElnagdy** [comment]
35407180-hc with the same issue `Could not retrieve Facebook Business Extension System User`, BUT the workaround from this [reply](https://github.com/woocommerce/facebook-for-woocommerce/issues/2148#issuecomment-1134605655) fixed it.

**Comment by wyter** [comment]
5326675-zen

**Comment by xue28** [comment]
5356609-zen

**Comment by sarbouw** [comment]
5392227-zen

**Comment by ericfri** [comment]
I've experienced this issue on a personal site and the workaround didn't work for me. What finally did work, was going into my [Business Manager](https://business.facebook.com/settings/product-catalogs) and removing the associated catalog. Then when the wizard ran, it created a new catalog and the process completed successfully.

**Comment by zepphub** [comment]
Hello,
Any update on this issue?
I am still having the same error (user_denied)

**Comment by Jumdeem** [comment]
Bonjour, le problème persiste toujours de mon côté...du nouveau ?
Merci

**Comment by rawdreeg** [comment]
> Any update on this issue?
> I am still having the same error (user_denied)

We're still talking to Meta about the reconnection issues. They're currently investigating the issue.

However, `user_denied` usually means a permission issue. I recommend you try removing the associated catalog. Then trying to reconnect, it should prompt you to create a new Catalog. If this does not work , I suggest you contact our support [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/).

**Comment by margaretgithub** [comment]
5523846-zen

**Comment by ericfri** [comment]
5526898-zen

**Comment by fritzdanny** [comment]
Hello, 
when will the problem be fixed about?

Thx

**Comment by rawdreeg** [comment]
We're still talking to Meta about the reconnection issues. They're currently investigating.

Some users have had some luck with the solution suggested [here](https://github.com/woocommerce/facebook-for-woocommerce/issues/2148#issuecomment-1191031895). If this does not work, I suggest you contact our support [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/).

**Comment by PortiaC** [comment]
I was stuck on this issue for hours, none of the above worked for me however I managed to get it to work after doing this. 

You will need to go into your personal account settings on Facebook (https://www.facebook.com/settings?tab=security) and enable two-factor authentication. Once this has been done if you try to reconnect on woocommerce the error should disappear and you should be able to connect successfully.

No idea why this worked for me but let me know if you have any luck!

**Comment by melek** [comment]
@PortiaC Two-factor authentication should be enabled for the plugin to work with accounts older than 90 days, so that was a great move! I think it is worthwhile to mention for future folks thinking they are affected by this bug to make sure they have it enabled. I wonder if businesses set up without 2fa enabled in the first 90 days of the account opening might have something to do with the error after the 90 day period has elapsed.

Doc: https://woocommerce.com/document/facebook-for-woocommerce/#two-factor-authentication

**Comment by Babylon1999** [comment]
zd-5565131

Forum: https://wordpress.org/support/topic/error-when-trying-to-connect-woocommerce-to-facebook/#post-16020989

**Comment by mpmedialab** [comment]
5588877-zd
https://wordpress.org/support/topic/facebook-plugin-conenction-issue-2/

**Comment by ericfri** [comment]
5593288-zen

**Comment by lynnjat7** [comment]
5662787-zd

**Comment by anastas10s-afk** [comment]
Also here: https://wordpress.org/support/topic/woocommerce-and-facebook-integration-failure/

**Comment by ericfri** [comment]
5690772-zen

**Comment by Babylon1999** [comment]
One more here: https://wordpress.org/support/topic/could-not-retrieve-facebook-business-extension-system-user-10/#post-16193788

zd-5708183

**Comment by taftina** [comment]
5735989-zd

**Comment by ericfri** [comment]
5760844-zen

**Comment by scherfro** [comment]
Fore the problem **Could not retrieve Facebook Business Extension System User** this is the solution:

- Navigate to https://business.facebook.com/latest/business_app_store/
- Select the WooCommerce Integration and click on Manage
- Where you see this text "**There are more features available to you**" click on See features
- Connect to WooCommerce Integration window pops up
- click continue, enter your website and connect and then finish the remaining setup steps

**Comment by mullerjk** [comment]
> here

This worked for me, thanks! :)

**Comment by thracefulton** [comment]
>Fore the problem Could not retrieve Facebook Business Extension System User this is the solution:

Confirmed this process worked for a user today! 👍

**Comment by rawdreeg** [comment]
We have received confirmation from Meta that they've released a fix to the connection that should fix this issue for most users. However, if you're still experiencing this issue, please try one of the following [solutions](https://woocommerce.com/document/facebook-for-woocommerce/#section-29) or contact the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/). Or, if you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

**Comment by sukafia** [comment]
New case in 6028656-zen 

![tG8N7i.png](https://user-images.githubusercontent.com/60121732/225535206-00359e08-cb95-4212-856a-995798db0188.png)

![BZvjWF.png](https://user-images.githubusercontent.com/60121732/225535229-5b159d67-b6d6-4e1f-bb64-ce609a901fac.png)

**Comment by rawdreeg** [comment]
Hi @sukafia,

Looking at the screenshot, it seems like their not connecting to our FB app (WooCommerce Integration); instead, they're trying to connect to an app called `WooCommerce Extension V2 - Business Manager`. This could be caused by stale configurations. But clearing Facebook settings on the site would be a good first step.
